---
deployment:
  tasks:
    - export DEPLOYPATH=/home/tjsserve/public_html/api.tjs-server.com
    - export REPOPATH=/home/tjsserve/repo/frame-project
    - /bin/cp -R public/build $DEPLOYPATH
    - /bin/cp -R public/images $DEPLOYPATH
    - /bin/cp -R public/vendor $DEPLOYPATH
